version: '3.7'

services:
  go-api:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o api ./cmd/api" -command="./api" --graceful-kill=true -color=true
    environment:
      - API_ADDR=:8000
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=payments
    volumes:
      - .:/app
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8000:8000

  go-web:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o web ./cmd/web" -command="./web" --graceful-kill=true -color=true
    environment:
      - WEB_ADDR=:8080
      - API_ADDR=http://go-api:8000
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8080:8080

  ping:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o ping ./cmd/ping" -command="./ping" --graceful-kill=false -color=true
    volumes:
      - type: bind
        source: .
        target: /app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '5s'
        fluentd-max-retries: '30'
        tag: payments.service.ping

  go-notification:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o notification ./cmd/notification" -command="./notification" --graceful-kill=true -color=true
    volumes:
      - .:/app

  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: payments
    ports:
      - 54320:5432

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 1025:25

  rabbitmq:
    image: rabbitmq:3.7.17-management-alpine
    ports:
      - 15672:15672

  elasticsearch:
    image: elasticsearch:6.8.3
    expose:
      - 9200
    ports:
      - 9200:9200
    environment:
      - cluster.name=go-payments-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: false #flag to disable copying of data from a container when a volume is created

  kibana:
    image: kibana:6.8.3
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  fluentd:
    build:
      context: .
      dockerfile: .docker/fluentd/Dockerfile
    volumes:
      - type: bind
        source: .docker/fluentd/conf/fluent.conf
        target: /fluentd/etc/fluent.conf
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp


volumes:
  postgres_data:
    driver: local
    name: "go-payments-postgres"
  elasticsearch_data:
    driver: local
    name: "go-payments-elasticsearch"

