version: '3.7'

services:
  migration:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
      args:
        install_goose: "on"
    volumes:
      - type: bind
        source: ./migrations
        target: /migrations
    networks:
      - go_payments

  api:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o api ./cmd/api" -command="./api" --graceful-kill=true -color=true
    environment:
      - API_ADDR=:8000
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=payments
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - postgres
      - fluentd
      - rabbitmq
    links:
      - postgres
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - go_payments

  web:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o web ./cmd/web" -command="./web" --graceful-kill=true -color=true
    environment:
      - WEB_ADDR=:8080
      - API_ADDR=http://api:8000
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - 8080:8080
    networks:
      - go_payments

  ping:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o ping ./cmd/ping" -command="./ping" --graceful-kill=false -color=true
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '5s'
        fluentd-max-retries: '30'
        tag: payments.service.ping
    networks:
      - go_payments

  notification:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: CompileDaemon -log-prefix=false -build="go build -o notification ./cmd/notification" -command="./notification" --graceful-kill=true -color=true
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '5s'
        fluentd-max-retries: '30'
        tag: payments.service.notification
    networks:
      - go_payments

  postgres:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: payments
    expose:
      - 5432
    ports:
      - 54320:5432
    networks:
      - go_payments

  maildev:
    image: djfarrelly/maildev
    expose:
      - 1025
    ports:
      - 1081:80
    networks:
      - go_payments

  rabbitmq:
    image: rabbitmq:3.7.17-management-alpine
    expose:
      - 5672
    ports:
      - 15672:15672
    networks:
      - go_payments

  elasticsearch:
    image: elasticsearch:6.8.3
    expose:
      - 9200
#    ports:
#      - 9200:9200
    environment:
      - cluster.name=go-payments-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
        volume:
          nocopy: false #flag to disable copying of data from a container when a volume is created
    networks:
      - go_payments

  kibana:
    image: kibana:6.8.3
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - go_payments

  fluentd:
    build:
      context: .
      dockerfile: .docker/fluentd/Dockerfile
    volumes:
      - type: bind
        source: .docker/fluentd/conf/fluent.conf
        target: /fluentd/etc/fluent.conf
    #links:
    #  - elasticsearch
    #depends_on:
    #  - elasticsearch
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - go_payments


volumes:
  postgres_data:
    driver: local
    name: "go-payments-postgres"
  elasticsearch_data:
    driver: local
    name: "go-payments-elasticsearch"


networks:
  go_payments:
    driver: bridge
    name: "go_payments"