version: '3.7'

services:
  payments-postgres:
    image: postgres:11
    container_name: payments-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: payments
    ports:
      - 54320:5432

  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 1025:25


volumes:
  postgres_data:

